apiVersion: v1
name: openlist
version: 0.1.1
appVersion: v4.1.6
description: OpenList is a resilient, long-term governance, community-driven fork of AList - built to defend open source against trust-based attacks.
keywords:
- openlist
sources:
- https://github.com/OpenListTeam/OpenList.git
home: https://oplist.org/
icon: https://raw.githubusercontent.com/OpenListTeam/Logo/main/logo.svg